### ISSUE TITLE
[FEATURE REQUEST] [DOC] Add CONTRIBUTING.md

### ISSUE THREAD

**Issue by inclinedadarsh** [inclinedadarsh/timeloom-old#15]
**Is your feature request related to a problem? Please describe.**
No guide is available for new contributors.

**Describe the solution you'd like**
Write a clear and concise `CONTRIBUTING.md` for new contributors.
It should include the following points: 
- Read all the other `.md` files such as `README.md`, `CODE_OF_CONDUCT.md`, etc. before contributing.
- Add step by step instructions to fork, clone, create a branch, make changes, push to fork and open a PR.
- Add the tech stack of the project in the description: NextJS + TypeScript
- Add all other necessary things in the `CONTRIBUTING.md` file (try to read other projects' `CONTRIBUTING.md` to see what else is required

**Comment by An-Array** [comment]
Can you assign me this? I would like to work on it.  @inclinedadarsh

**Comment by inclinedadarsh** [comment]
Sure. Go ahead @An-Array, I have assigned this to you.
Let me know if you need any help.

**Comment by An-Array** [comment]
@inclinedadarsh hey I have raised a PR for CONTRIBUTING.md can you check and tell me if it's okay or if any changes are needed?
