### ISSUE TITLE
[FEATURE REQUEST] Light mode

### ISSUE THREAD

**Issue by inclinedadarsh** [inclinedadarsh/timeloom-old#9]

**Comment by rjwignar** [comment]
I would like to work on this feature.
Please assign it to me.

**Comment by inclinedadarsh** [comment]
Go ahead @rjwignar 
I have assigned this to you.

I'm here for any assistance you need.
Thank you for your interest!

**Comment by rjwignar** [comment]
Thank you.
So far I've extended the UI to use light/dark mode according to the user's system preferences.
Right now I'm working on the light mode styling.
![image](https://github.com/inclinedadarsh/timeloom/assets/78163326/401a3aa8-a0e3-4f11-81b4-089456de9418)

I should have a PR later today.

However, I'm not sure of the best way to proceed with the grid image for light mode:
![image](https://github.com/inclinedadarsh/timeloom/assets/78163326/9c7cd7ac-1221-4e7e-a82f-9389ff958955)

I understand the white grid image is from `@/assets/bg-grid.png`, but I can't seem to modify the image color using code.
Do you know of a way to do this without adding a new image to the project?

**Comment by inclinedadarsh** [comment]
This is looking good @rjwignar 

For the `bg-grid.png`, we can do 2 things, choose whichever option you like:
1. Leave it for now & open a separate issue for that. 
2. I'll give you access to the Figma, you make a light-mode version of it and use it in the assets as well. Write logic to show respective versions when in light or dark mode.

**Comment by rjwignar** [comment]
I can't guarantee if I can replicate the exact effect you have in the original, but I can try making a light-version of it using the figma and include it in my PR.

Then depending on how you like it we can keep it remove it from the PR.
If sharing the figma requires an email you can share it to this email address: rjwignarajah@myseneca.ca
